[package]
name = "ouroboros"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[dependencies]
glfw = "*"
glfw-sys = { version = "*", default-features = false, features = [
  "x11",
  "src-build",
] }
